jobs:
  build-and-test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Show destinations (debug)
        run: |
          xcodebuild -project RickMortyLLM.xcodeproj -scheme RickMortyLLM -showdestinations || true

      - name: Pick an iOS Simulator by UDID (from -showdestinations)
        id: pick
        shell: bash
        run: |
          # Get the first iOS Simulator id from -showdestinations output
          SIM_ID=$(xcodebuild -project RickMortyLLM.xcodeproj -scheme RickMortyLLM -showdestinations \
            | sed -n 's/.*platform:iOS Simulator, id:[[:space:]]*\([^,}]*\).*/\1/p' \
            | head -n1)

          if [ -z "$SIM_ID" ]; then
            echo "No iOS Simulator destination found for this scheme"; exit 1
          fi

          echo "Picked simulator id: $SIM_ID"
          echo "sim_id=$SIM_ID" >> "$GITHUB_OUTPUT"

      - name: Cache SPM
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            ~/Library/Caches/org.swift.swiftpm
            ~/.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-spm-


      - name: Build & Test (using picked simulator)
        run: |
          set -o pipefail
          xcodebuild \
            -project RickMortyLLM.xcodeproj \
            -scheme RickMortyLLM \
            -destination "id=${{ steps.pick.outputs.sim_id }}" \
            -derivedDataPath DerivedData \
            -skipPackagePluginValidation \
            -parallel-testing-enabled YES \
            -enableCodeCoverage YES \
            -resultBundlePath TestResults.xcresult \
            clean test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults.xcresult
          path: TestResults.xcresult
