jobs:
  build-and-test:
    runs-on: macos-14     # or macos-15 if your org has it
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'   # ensure this exists on the runner

      - name: Install jq (for device picking)
        run: brew install jq

      - name: Show Xcode & Simulators
        run: |
          xcodebuild -version
          xcodebuild -showsdks
          xcrun simctl list devices

      - name: Pick an available iPhone simulator
        id: pick
        shell: bash
        run: |
          json=$(xcrun simctl list devices --json)
          # Prefer newest iPhone names; fall back to any available iPhone
          name=$(echo "$json" | jq -r '
            .devices | to_entries[].value[]
            | select(.isAvailable == true)
            | .name
          ' | grep -E "iPhone 1(6|5)|iPhone SE|iPhone" | head -n1)
          if [ -z "$name" ]; then
            echo "No iPhone simulator found"; exit 1
          fi
          echo "device=$name" >> "$GITHUB_OUTPUT"
          echo "Picked: $name"

      - name: Cache SPM
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            ~/Library/Caches/org.swift.swiftpm
            ~/.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-spm-

      - name: Build & Test (Simulator)
        run: |
          set -o pipefail
          xcodebuild \
            -project RickMortyLLM.xcodeproj \
            -scheme RickMortyLLM \
            -destination "platform=iOS Simulator,OS=latest,name=${{ steps.pick.outputs.device }}" \
            -derivedDataPath DerivedData \
            -skipPackagePluginValidation \
            -parallel-testing-enabled YES \
            -enableCodeCoverage YES \
            -resultBundlePath TestResults.xcresult \
            clean test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults.xcresult
          path: TestResults.xcresult
