name: iOS CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
concurrency:
  group: ios-${{ github.ref }}
  cancel-in-progress: true
jobs:
  unit-tests:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Select Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'
      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: |
            ~/.swiftpm
            ~/Library/Caches/org.swift.swiftpm
            ~/Library/Developer/Xcode/DerivedData/**/SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-spm-
      - name: Show available destinations (debug)
        run: |
          xcodebuild -project RickMortyLLM.xcodeproj -scheme RickMortyLLM -showdestinations || true
      # Build once for any iOS simulator (fast & reliable)
      - name: Build for Testing (generic sim)
        run: |
          set -euo pipefail
          xcodebuild \
            -project RickMortyLLM.xcodeproj \
            -scheme RickMortyLLM \
            -destination 'generic/platform=iOS Simulator' \
            -derivedDataPath DerivedData \
            -skipPackagePluginValidation \
            COMPILER_INDEX_STORE_ENABLE=NO \
            build-for-testing
      